import React, { useState } from 'react';
import { 
  Bell, 
  AlertTriangle, 
  Radio, 
  Send, 
  CheckCircle2, 
  Clock, 
  ShieldAlert,
  Volume2,
  Megaphone
} from 'lucide-react';
import { SystemExecutionState } from '../types/disaster';

interface AlertsViewProps {
  state: SystemExecutionState | null;
  onStateUpdate?: (newState: SystemExecutionState) => void;
}

export const AlertsView: React.FC<AlertsViewProps> = ({ state, onStateUpdate }) => {
  const [targetZone, setTargetZone] = useState<string>('Zone C');
  const [alertLevel, setAlertLevel] = useState<string>('CRITICAL');
  const [customMessage, setCustomMessage] = useState<string>('');
  const [isBroadcasting, setIsBroadcasting] = useState<boolean>(false);
  const [broadcastSuccess, setBroadcastSuccess] = useState<string | null>(null);

  if (!state) return null;

  const isDamFailure = state.activeEmergencyId?.includes('DAM') || state.activeEmergencyId?.includes('EMERGENCY');
  const zones = state.zones || [];
  const coordinatorAlert = state.coordinatorOutput?.public_alert;
  const communicationWarning = state.communicationOutput?.public_warning;

  // Active public alerts generated by Communication Agent / Coordinator
  const activeAlerts = [
    {
      id: 'ALT-01',
      level: isDamFailure ? 'CRITICAL' : 'DANGER',
      zone: isDamFailure ? 'Zone C & Zone B' : 'Zone B',
      message: coordinatorAlert || communicationWarning || 'Residents in Zone B and surrounding areas must seek immediate shelter. Avoid coastal road arteries.',
      issuedTime: '14:32',
      status: 'ACTIVE',
      channel: 'Cell Broadcast, Siren Mesh, Emergency Radio',
    },
    {
      id: 'ALT-02',
      level: 'MEDIUM',
      zone: 'Zone A',
      message: 'Highway 102 transit corridor prioritized for emergency rescue vehicles. Civilian non-emergency transit restricted.',
      issuedTime: '14:28',
      status: 'ACTIVE',
      channel: 'Highway Matrix Displays',
    },
  ];

  const handleBroadcastAlert = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!customMessage.trim()) return;

    setIsBroadcasting(true);
    setBroadcastSuccess(null);

    // Simulate real alert broadcast through communication bus
    setTimeout(() => {
      setIsBroadcasting(false);
      setBroadcastSuccess(`Alert successfully broadcast to ${targetZone} via cellular emergency channels.`);
      setCustomMessage('');
    }, 600);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-800 pb-5">
        <div>
          <h1 className="text-xl sm:text-2xl font-black text-white tracking-tight">
            Alerts
          </h1>
          <p className="text-xs text-slate-400 mt-1">
            Real-time public warnings generated by Communication Agent and multi-channel broadcast status
          </p>
        </div>

        <div className="flex items-center gap-2">
          <span className="px-2.5 py-1 rounded text-xs font-mono font-bold bg-red-950 text-red-300 border border-red-800 flex items-center gap-1.5">
            <span className="w-2 h-2 rounded-full bg-red-400 animate-pulse" />
            2 ACTIVE BROADCASTS
          </span>
        </div>
      </div>

      {broadcastSuccess && (
        <div className="p-3.5 rounded-xl bg-slate-900 border border-emerald-700/60 text-xs text-emerald-300 flex items-center justify-between font-mono">
          <span>✓ {broadcastSuccess}</span>
          <button onClick={() => setBroadcastSuccess(null)} className="text-slate-400 hover:text-white cursor-pointer ml-2">
            Dismiss
          </button>
        </div>
      )}

      {/* SECTION 15: REAL-TIME PUBLIC ALERTS LIST */}
      <div className="space-y-4">
        {activeAlerts.map((alert) => (
          <div key={alert.id} className="p-5 rounded-xl bg-slate-900 border border-slate-800 space-y-3">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-slate-800 pb-3">
              <div className="flex items-center gap-2.5">
                <span
                  className={`px-2 py-0.5 rounded text-[11px] font-mono font-bold ${
                    alert.level === 'CRITICAL'
                      ? 'bg-red-950 text-red-300 border border-red-800'
                      : alert.level === 'DANGER'
                      ? 'bg-orange-950 text-orange-300 border border-orange-800'
                      : 'bg-amber-950 text-amber-300 border border-amber-800'
                  }`}
                >
                  {alert.level}
                </span>
                <span className="text-sm font-bold text-white font-mono">{alert.zone}</span>
              </div>

              <div className="flex items-center gap-3 text-xs font-mono">
                <span className="text-slate-400 flex items-center gap-1">
                  <Clock className="w-3.5 h-3.5" /> Issued: {alert.issuedTime}
                </span>
                <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-emerald-950 text-emerald-300 border border-emerald-800">
                  STATUS: {alert.status}
                </span>
              </div>
            </div>

            <p className="text-sm text-slate-200 font-medium leading-relaxed">
              "{alert.message}"
            </p>

            <div className="flex items-center justify-between pt-1 text-[11px] font-mono text-slate-400">
              <span className="flex items-center gap-1.5">
                <Radio className="w-3.5 h-3.5 text-cyan-400" />
                Channels: {alert.channel}
              </span>
              <span className="text-slate-400">Source: Communication Agent</span>
            </div>
          </div>
        ))}
      </div>

      {/* CREATE ALERT / BROADCAST INTERFACE */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-4">
        <div className="border-b border-slate-800 pb-3">
          <h2 className="text-sm font-bold text-white uppercase tracking-wider flex items-center gap-2">
            <Megaphone className="w-4 h-4 text-cyan-400" />
            Create Alert
          </h2>
          <p className="text-xs text-slate-400 mt-0.5">
            Issue emergency public advisory through municipal communication gateways
          </p>
        </div>

        <form onSubmit={handleBroadcastAlert} className="space-y-4 text-xs">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="text-slate-400 font-mono text-[11px] block mb-1.5">Target Zone</label>
              <select
                value={targetZone}
                onChange={(e) => setTargetZone(e.target.value)}
                className="w-full bg-slate-950 border border-slate-700 rounded-lg p-2.5 text-white font-mono text-xs focus:outline-hidden focus:border-cyan-500 cursor-pointer"
              >
                {zones.map((z) => {
                  const zoneName = z.name || z.id || (z as any).zone || 'Zone';
                  return (
                    <option key={z.id || zoneName} value={zoneName}>
                      {zoneName}
                    </option>
                  );
                })}
              </select>
            </div>

            <div>
              <label className="text-slate-400 font-mono text-[11px] block mb-1.5">Alert Level</label>
              <select
                value={alertLevel}
                onChange={(e) => setAlertLevel(e.target.value)}
                className="w-full bg-slate-950 border border-slate-700 rounded-lg p-2.5 text-white font-mono text-xs focus:outline-hidden focus:border-cyan-500 cursor-pointer"
              >
                <option value="CRITICAL">CRITICAL (Immediate Life Threat)</option>
                <option value="DANGER">DANGER (Evacuation Recommended)</option>
                <option value="MEDIUM">MEDIUM (Advisory & Road Closure)</option>
              </select>
            </div>
          </div>

          <div>
            <label className="text-slate-400 font-mono text-[11px] block mb-1.5">Alert Advisory Message</label>
            <textarea
              rows={3}
              value={customMessage}
              onChange={(e) => setCustomMessage(e.target.value)}
              placeholder="Enter clear, concise public advisory instructions..."
              className="w-full bg-slate-950 border border-slate-700 rounded-lg p-3 text-white font-mono text-xs focus:outline-hidden focus:border-cyan-500"
            />
          </div>

          <div className="flex justify-end">
            <button
              type="submit"
              disabled={isBroadcasting || !customMessage.trim()}
              className="flex items-center space-x-2 px-5 py-2.5 rounded-lg text-xs font-semibold bg-red-600 hover:bg-red-500 text-white transition cursor-pointer disabled:opacity-50"
            >
              <Send className="w-3.5 h-3.5" />
              <span>{isBroadcasting ? 'Broadcasting...' : 'Broadcast Emergency Alert'}</span>
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};
