import {
  SystemExecutionState,
  Zone,
  ResourceUnit,
  RescuePassport,
  ApprovalState,
  PrimaryBackupPlan,
  WhatIfScenario,
  DataHealthField,
  ConflictingReport,
  IncidentMemoryEntry,
  CauseChainNode,
  AuditTrailEntry,
} from '../types/disaster';

export const INITIAL_ZONES: Zone[] = [
  {
    id: 'Zone A',
    name: 'Industrial Corridor & North Residential',
    population: 4200,
    peopleAtRisk: 340,
    injured: 6,
    severity: 'HIGH',
    emergencyType: 'Toxic Plume Dispersion & Road Obstruction',
    requiredResources: ['Rescue Vehicle', 'Ambulance', 'Medical Kits', 'Shelter North'],
    coordinates: { x: 22, y: 30 },
    notes: 'Chemical plant storage tank rupture. Southwesterly wind blowing airborne particulates toward residential sectors. Road Alpha partially blocked by debris.',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'Zone B',
    name: 'Downtown Commercial / Transit Hub',
    population: 6800,
    peopleAtRisk: 580,
    injured: 18,
    severity: 'CRITICAL',
    emergencyType: 'Multi-Story Structural Collapse & Fire',
    requiredResources: ['Ambulance (AMB-02)', 'Medical Team (MED-T1)', 'Rescue Vehicle', 'Medical Kits'],
    coordinates: { x: 68, y: 28 },
    notes: 'Building facade and subterranean concourse collapse during seismic tremor. Multiple trapped victims with crush injuries and severe hypovolemic trauma.',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'Zone C',
    name: 'River Valley & Waterfront Basin',
    population: 3100,
    peopleAtRisk: 140,
    injured: 2,
    severity: 'MODERATE',
    emergencyType: 'Rising Water Table & Drainage Backflow',
    requiredResources: ['Rescue Boats', 'Food & Water Packs'],
    coordinates: { x: 38, y: 72 },
    notes: 'Lowland storm drain surcharge. Retaining dyke holding stable at 78% capacity prior to upstream reservoir alert.',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'Zone D',
    name: 'West Hills Suburbs & Forest Margin',
    population: 2900,
    peopleAtRisk: 80,
    injured: 1,
    severity: 'LOW',
    emergencyType: 'Isolated Power Grid Outage / Sensor Blackout',
    requiredResources: ['Food Packs', 'Water Packs'],
    coordinates: { x: 80, y: 78 },
    notes: 'Transformer fire isolated. Minimal structural hazard; local shelter capable of supporting self-evacuees.',
    lastUpdated: new Date().toISOString(),
  },
];

export const INITIAL_RESOURCES: ResourceUnit[] = [
  {
    id: 'AMB-01',
    type: 'Ambulance',
    name: 'Paramedic Rapid Response Ambulance 01',
    total: 1,
    available: 1,
    allocated: 0,
    status: 'AVAILABLE',
    capacity: 2,
    offRoad: false,
    medicalSupport: true,
    fuelPercent: 88,
    locationGps: 'Sector 4 Base (34.052, -118.243)',
    reservationStatus: 'AVAILABLE',
  },
  {
    id: 'AMB-02',
    type: 'Ambulance',
    name: 'Advanced Life Support Ambulance 02',
    total: 1,
    available: 1,
    allocated: 0,
    status: 'AVAILABLE',
    capacity: 4,
    offRoad: true,
    medicalSupport: true,
    fuelPercent: 95,
    locationGps: 'Central Station (34.056, -118.251)',
    reservationStatus: 'AVAILABLE',
  },
  {
    id: 'RV-01',
    type: 'Rescue Vehicle',
    name: 'Heavy Structural Extrication Truck 01',
    total: 1,
    available: 1,
    allocated: 0,
    status: 'AVAILABLE',
    capacity: 8,
    offRoad: true,
    medicalSupport: false,
    fuelPercent: 74,
    locationGps: 'Fire Dept HQ (34.061, -118.239)',
    reservationStatus: 'AVAILABLE',
  },
  {
    id: 'RV-02',
    type: 'Rescue Vehicle',
    name: 'Hazmat Decontamination Rig 02',
    total: 1,
    available: 1,
    allocated: 0,
    status: 'AVAILABLE',
    capacity: 6,
    offRoad: false,
    medicalSupport: true,
    fuelPercent: 82,
    locationGps: 'Industrial Substation (34.048, -118.229)',
    reservationStatus: 'AVAILABLE',
  },
  {
    id: 'RV-03',
    type: 'Rescue Vehicle',
    name: 'All-Terrain Rough-Access Tender 03',
    total: 1,
    available: 1,
    allocated: 0,
    status: 'AVAILABLE',
    capacity: 12,
    offRoad: true,
    medicalSupport: false,
    fuelPercent: 91,
    locationGps: 'West Hills Depot (34.072, -118.271)',
    reservationStatus: 'AVAILABLE',
  },
  {
    id: 'MED-T1',
    type: 'Medical Team',
    name: 'Disaster Surgical Triage Team Alpha',
    total: 1,
    available: 1,
    allocated: 0,
    status: 'AVAILABLE',
    membersCount: 4,
    traumaCapability: true,
    reservationStatus: 'AVAILABLE',
  },
  {
    id: 'MED-T2',
    type: 'Medical Team',
    name: 'Critical Care Trauma Unit Bravo',
    total: 1,
    available: 1,
    allocated: 0,
    status: 'AVAILABLE',
    membersCount: 3,
    traumaCapability: true,
    reservationStatus: 'AVAILABLE',
  },
  {
    id: 'MED-T3',
    type: 'Medical Team',
    name: 'Field Resuscitation Team Charlie',
    total: 1,
    available: 1,
    allocated: 0,
    status: 'AVAILABLE',
    membersCount: 3,
    traumaCapability: false,
    reservationStatus: 'AVAILABLE',
  },
  {
    id: 'MED-T4',
    type: 'Medical Team',
    name: 'Emergency Medical Service Squad Delta',
    total: 1,
    available: 1,
    allocated: 0,
    status: 'AVAILABLE',
    membersCount: 2,
    traumaCapability: false,
    reservationStatus: 'AVAILABLE',
  },
  {
    id: 'MED-T5',
    type: 'Medical Team',
    name: 'Pediatric & Geriatric Care Unit Echo',
    total: 1,
    available: 1,
    allocated: 0,
    status: 'AVAILABLE',
    membersCount: 3,
    traumaCapability: false,
    reservationStatus: 'AVAILABLE',
  },
  {
    id: 'MED-KITS',
    type: 'Medical Kit',
    name: 'Trauma & Airway Burn First-Aid Kits',
    total: 20,
    available: 20,
    allocated: 0,
    status: 'AVAILABLE',
    reservationStatus: 'AVAILABLE',
  },
  {
    id: 'RB-01',
    type: 'Rescue Boat',
    name: 'Swift-Water Inflatable Jet Boat 01',
    total: 1,
    available: 1,
    allocated: 0,
    status: 'AVAILABLE',
    capacity: 6,
    offRoad: true,
    fuelPercent: 100,
    locationGps: 'River Marina (34.038, -118.221)',
    reservationStatus: 'AVAILABLE',
  },
  {
    id: 'RB-02',
    type: 'Rescue Boat',
    name: 'Rigid-Hull Flood Evacuation Craft 02',
    total: 1,
    available: 1,
    allocated: 0,
    status: 'AVAILABLE',
    capacity: 10,
    offRoad: true,
    fuelPercent: 85,
    locationGps: 'Harbor Gate 2 (34.032, -118.215)',
    reservationStatus: 'AVAILABLE',
  },
  {
    id: 'SH-North',
    type: 'Shelter',
    name: 'North Community Arena Shelter',
    total: 1,
    available: 1,
    allocated: 0,
    status: 'AVAILABLE',
    capacity: 500,
    reservationStatus: 'AVAILABLE',
  },
  {
    id: 'SH-Central',
    type: 'Shelter',
    name: 'Central High School Gymnasium',
    total: 1,
    available: 1,
    allocated: 0,
    status: 'AVAILABLE',
    capacity: 650,
    reservationStatus: 'AVAILABLE',
  },
  {
    id: 'SH-South',
    type: 'Shelter',
    name: 'South Fairgrounds Pavilion',
    total: 1,
    available: 1,
    allocated: 0,
    status: 'AVAILABLE',
    capacity: 400,
    reservationStatus: 'AVAILABLE',
  },
  {
    id: 'FOOD-100',
    type: 'Food Pack',
    name: 'Ready-to-Eat Emergency Ration Crates',
    total: 100,
    available: 100,
    allocated: 0,
    status: 'AVAILABLE',
  },
  {
    id: 'WATER-200',
    type: 'Water Pack',
    name: 'Purified Emergency Drinking Water Units',
    total: 200,
    available: 200,
    allocated: 0,
    status: 'AVAILABLE',
  },
];

export const INITIAL_PASS_PORTS: RescuePassport[] = [
  {
    incidentId: 'INC-B-01',
    location: 'Zone B — Downtown Concourse & Transit Plaza',
    affectedPeople: 580,
    reportedInjuries: 18,
    priority: 'CRITICAL',
    assignedVehicle: 'AMB-02 (ALS Ambulance)',
    assignedMedicalTeam: 'MED-T1 (Surgical Triage)',
    assignedShelter: 'SH-Central (High School Gym)',
    stage: 'APPROVAL',
    stageStatus: {
      PLAN: 'COMPLETED',
      APPROVAL: 'IN_PROGRESS',
      DISPATCH: 'PENDING',
      IN_TRANSIT: 'PENDING',
      ARRIVAL: 'PENDING',
      HELP_RECEIVED: 'PENDING',
      COMPLETED: 'PENDING',
    },
    helpReceivedStatus: 'PENDING_VERIFICATION',
    updatedAt: new Date().toISOString(),
  },
  {
    incidentId: 'INC-A-01',
    location: 'Zone A — Industrial Corridor Chem Storage',
    affectedPeople: 340,
    reportedInjuries: 6,
    priority: 'HIGH',
    assignedVehicle: 'RV-01 (Extrication Rig)',
    assignedMedicalTeam: 'MED-T2 (Trauma Bravo)',
    assignedShelter: 'SH-North (Community Arena)',
    stage: 'PLAN',
    stageStatus: {
      PLAN: 'COMPLETED',
      APPROVAL: 'PENDING',
      DISPATCH: 'PENDING',
      IN_TRANSIT: 'PENDING',
      ARRIVAL: 'PENDING',
      HELP_RECEIVED: 'PENDING',
      COMPLETED: 'PENDING',
    },
    helpReceivedStatus: 'PENDING_VERIFICATION',
    updatedAt: new Date().toISOString(),
  },
  {
    incidentId: 'INC-C-01',
    location: 'Zone C — River Valley Waterfront Basin',
    affectedPeople: 140,
    reportedInjuries: 2,
    priority: 'MEDIUM',
    assignedVehicle: 'RB-01 (Swift Jet Boat)',
    assignedMedicalTeam: 'MED-T3 (Field Team Charlie)',
    assignedShelter: 'SH-South (Fairgrounds)',
    stage: 'PLAN',
    stageStatus: {
      PLAN: 'COMPLETED',
      APPROVAL: 'PENDING',
      DISPATCH: 'PENDING',
      IN_TRANSIT: 'PENDING',
      ARRIVAL: 'PENDING',
      HELP_RECEIVED: 'PENDING',
      COMPLETED: 'PENDING',
    },
    helpReceivedStatus: 'PENDING_VERIFICATION',
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_APPROVAL_STATE: ApprovalState = {
  status: 'PENDING_APPROVAL',
  approverName: 'Cmdr. Elena Vance',
  approverRole: 'Authorized Emergency Response Officer',
  timestamp: new Date().toISOString(),
  reason: 'Initial multi-agent synthesis awaiting human authorization before vehicle dispatch.',
};

export const INITIAL_PRIMARY_BACKUP_PLANS: PrimaryBackupPlan[] = [
  {
    incidentId: 'INC-B-01',
    targetZone: 'Zone B',
    primary: {
      vehicle: 'AMB-02',
      medicalTeam: 'MED-T1',
      route: 'Route Alpha-Direct (Central Blvd)',
      routeRisk: 'LOW RISK',
      distanceKm: 4.2,
      etaMinutes: 8,
      available: true,
    },
    backup: {
      vehicle: 'AMB-01',
      medicalTeam: 'MED-T2',
      route: 'Route Bravo-Perimeter (4th Ave Bridge)',
      routeRisk: 'MEDIUM RISK',
      distanceKm: 6.8,
      etaMinutes: 14,
      available: true,
    },
    activePlan: 'PRIMARY',
  },
  {
    incidentId: 'INC-A-01',
    targetZone: 'Zone A',
    primary: {
      vehicle: 'RV-01',
      medicalTeam: 'MED-T2',
      route: 'Route North-Corridor',
      routeRisk: 'MEDIUM RISK',
      distanceKm: 5.1,
      etaMinutes: 11,
      available: true,
    },
    backup: {
      vehicle: 'RV-02',
      medicalTeam: 'MED-T3',
      route: 'Route West-Bypass Expressway',
      routeRisk: 'LOW RISK',
      distanceKm: 7.4,
      etaMinutes: 16,
      available: true,
    },
    activePlan: 'PRIMARY',
  },
];

export const INITIAL_WHAT_IF_SCENARIOS: WhatIfScenario[] = [
  {
    id: 'SCENARIO-VEHICLE-FAIL',
    name: 'Primary Vehicle Breakdown (AMB-02 Mechanical Stop)',
    description: 'ALS Ambulance AMB-02 develops transmission failure en route to Zone B downtown collapse.',
    type: 'VEHICLE_FAILURE',
    currentCondition: 'AMB-02 deployed to Zone B; 8 min arrival window',
    simulatedCondition: 'AMB-02 halted at Mile 2.1. Zone B trauma patients without ALS support.',
    agentImpact: {
      medical: 'Escalate Zone B priority to EMERGENCY_CRITICAL; request alternate trauma transport.',
      logistics: 'Reroute backup vehicle AMB-01 from Station 4; dispatch heavy tow to clear corridor.',
      communication: 'Issue revised casualty transport advisory to receiving emergency trauma centers.',
      coordinator: 'Activate Backup Plan B: swap AMB-01 to Zone B and utilize RV-01 for stable transports.',
    },
    simulatedPlan: [
      {
        priority: 1,
        action: 'Dispatch Backup ALS AMB-01 to Zone B via 4th Ave Corridor',
        target_zone: 'Zone B',
        assigned_agent: 'Logistics Agent',
        details: 'Replaces disabled AMB-02; revised ETA 12 minutes.',
      },
      {
        priority: 2,
        action: 'Dispatch Heavy Tow Unit to recover AMB-02',
        target_zone: 'Zone B Corridor',
        assigned_agent: 'Logistics Agent',
        details: 'Pulls disabled vehicle out of main arterial route.',
      },
    ],
    resourceImpact: {
      vehicleDiff: 'AMB-02 (Unavailable) ➔ AMB-01 (Deployed)',
      medicDiff: 'MED-T1 re-staged on AMB-01',
      capacityState: 'TIGHT',
    },
  },
  {
    id: 'SCENARIO-ROAD-CLOSURE',
    name: 'Bridge Alpha Structural Closure',
    description: 'Seismic sensor detects severe hairline fracture on Bridge Alpha; artery closed immediately.',
    type: 'ROAD_CLOSURE',
    currentCondition: 'Bridge Alpha open to emergency vehicles; travel time 9 min',
    simulatedCondition: 'Bridge Alpha impassable; traffic diverted to West Ring Road (+15 min delay)',
    agentImpact: {
      medical: 'Adjust triage survival window for 3 hypovolemic patients in Zone A.',
      logistics: 'Reroute all Zone A hazmat and evacuation convoys via West Expressway.',
      communication: 'EAS alert warning motorists to avoid North River crossings.',
      coordinator: 'Designate secondary staging sector at North Fairgrounds.',
    },
    simulatedPlan: [
      {
        priority: 1,
        action: 'Reroute Zone A Convoy to West Ring Bypass',
        target_zone: 'Zone A',
        assigned_agent: 'Logistics Agent',
        details: 'Adds 3.4 km; bypasses compromised structural bridge span.',
      },
    ],
    resourceImpact: {
      vehicleDiff: 'Fuel consumption +18%',
      medicDiff: 'Field stabilization required pre-transport',
      capacityState: 'ADEQUATE',
    },
  },
  {
    id: 'SCENARIO-INJURY-SURGE',
    name: 'Sudden Casualty Surge in Zone B (18 ➔ 48 Trapped)',
    description: 'Aftershock triggers collapse of adjacent multi-story parking deck; casualty count surges.',
    type: 'INJURY_SURGE',
    currentCondition: '18 casualties in Zone B downtown concourse',
    simulatedCondition: '48 casualties reported, including 14 crush syndrome cases requiring immediate extrication',
    agentImpact: {
      medical: 'Request 3 additional medical teams and 20 extra trauma burn kits.',
      logistics: 'Requisition secondary municipal buses for minor ambulatory evacuations.',
      communication: 'Broadcast urgent blood donation appeal and major trauma hospital protocol.',
      coordinator: 'Declare Mass Casualty Incident Level 3; strip non-essential reserves from Zone D.',
    },
    simulatedPlan: [
      {
        priority: 1,
        action: 'Deploy All Available Medical Teams (MED-T1, MED-T2, MED-T3) to Zone B',
        target_zone: 'Zone B',
        assigned_agent: 'Medical Agent',
        details: 'Establish 3-tier field surgical tent at Downtown Plaza.',
      },
    ],
    resourceImpact: {
      vehicleDiff: 'All ambulances deployed; zero vehicle reserve remaining',
      medicDiff: '4 of 5 medical teams committed',
      capacityState: 'CRITICAL',
    },
  },
  {
    id: 'SCENARIO-SHELTER-FULL',
    name: 'Central High School Shelter Reaches 100% Capacity',
    description: 'Civilian self-evacuees overwhelm Central High School Gymnasium (650 / 650 beds full).',
    type: 'SHELTER_FULL',
    currentCondition: 'Central Shelter at 42% capacity',
    simulatedCondition: 'Central Shelter at 100% capacity; turning evacuees away at gate',
    agentImpact: {
      medical: 'Divert ambulatory wounded to South Fairgrounds triage.',
      logistics: 'Divert bus convoys to South Fairgrounds Pavilion (Capacity: 400).',
      communication: 'Update digital signs directing evacuees away from Central Shelter.',
      coordinator: 'Designate secondary shelter SH-South and request Red Cross cot delivery.',
    },
    simulatedPlan: [
      {
        priority: 1,
        action: 'Redirect Zone B evacuees to South Fairgrounds Pavilion',
        target_zone: 'Zone B / Shelter South',
        assigned_agent: 'Logistics Agent',
        details: 'Transfers 180 incoming evacuees to available shelter space.',
      },
    ],
    resourceImpact: {
      vehicleDiff: 'Extra bus shuttle needed for 4.2 km diversion',
      medicDiff: 'Deploy MED-T5 to South Fairgrounds for intake screening',
      capacityState: 'TIGHT',
    },
  },
];

export const INITIAL_DATA_HEALTH: DataHealthField[] = [
  {
    id: 'DH-01',
    field: 'Population Density',
    zone: 'Zone A',
    value: '4,200 residents',
    status: 'VERIFIED',
    source: 'Municipal Census & Smart Meter Feeds',
    timestamp: '12m ago',
    isUnknown: false,
  },
  {
    id: 'DH-02',
    field: 'Reported Injuries',
    zone: 'Zone B',
    value: '18 casualties',
    status: 'VERIFIED',
    source: 'FDNY On-Scene Battalion Chief Radio',
    timestamp: '4m ago',
    isUnknown: false,
  },
  {
    id: 'DH-03',
    field: 'River Water Gauge',
    zone: 'Zone C',
    value: '2.4 meters (Rising)',
    status: 'STALE',
    source: 'USGS Hydro Telemetry Sensor C-4',
    timestamp: '32m ago (Stale > 15m)',
    isUnknown: false,
  },
  {
    id: 'DH-04',
    field: 'Population Density',
    zone: 'Zone D',
    value: 'Unknown',
    status: 'UNKNOWN',
    source: 'Sensor Blackout — Do not assume zero',
    timestamp: 'N/A',
    isUnknown: true,
  },
  {
    id: 'DH-05',
    field: 'Injuries & Casualties',
    zone: 'Zone D',
    value: 'Unknown',
    status: 'UNKNOWN',
    source: 'No field responders deployed — Do not assume safe',
    timestamp: 'N/A',
    isUnknown: true,
  },
  {
    id: 'DH-06',
    field: 'Road Accessibility',
    zone: 'Zone A',
    value: 'Single Lane Open vs Impassable',
    status: 'CONFLICTING',
    source: 'Highway Patrol vs Citizen Video Feed',
    timestamp: '6m ago',
    isUnknown: false,
  },
  {
    id: 'DH-07',
    field: 'Cellular Connectivity',
    zone: 'Zone C',
    value: 'Degraded / 1 Tower Down',
    status: 'VERIFIED',
    source: 'Telco Network NOC Telemetry',
    timestamp: '8m ago',
    isUnknown: false,
  },
];

export const INITIAL_CONFLICTING_REPORTS: ConflictingReport[] = [
  {
    id: 'CR-01',
    topic: 'Zone B Trapped Population Count',
    zone: 'Zone B',
    sources: [
      { source: 'Civil Defense Regional Dispatch', reportedValue: 50, timestamp: '14:02', reliabilityScore: 0.85 },
      { source: 'Police Precinct Mobile Unit', reportedValue: 120, timestamp: '14:05', reliabilityScore: 0.72 },
      { source: 'Transit Concourse CCTV AI Estimator', reportedValue: 45, timestamp: '14:06', reliabilityScore: 0.91 },
    ],
    reportedRange: '45 – 120 people',
    status: 'VERIFICATION_REQUIRED',
    recommendedAction: 'Dispatch thermal drone reconnaissance to verify underground concourse crowding before allocating high-capacity bus fleet.',
  },
  {
    id: 'CR-02',
    topic: 'Zone A Road Alpha Navigability',
    zone: 'Zone A',
    sources: [
      { source: 'State Highway Patrol Dispatch', reportedValue: 'Completely blocked by downed high-voltage line', timestamp: '14:01', reliabilityScore: 0.9 },
      { source: 'Local Utility Maintenance Driver', reportedValue: 'North shoulder passable by heavy off-road rigs', timestamp: '14:07', reliabilityScore: 0.75 },
    ],
    reportedRange: 'Blocked vs Single Shoulder Passable',
    status: 'VERIFICATION_REQUIRED',
    recommendedAction: 'Hold civilian evacuation convoys; authorize off-road Rescue Vehicle RV-01 only after visual confirmation.',
  },
];

export const INITIAL_INCIDENT_MEMORY: IncidentMemoryEntry[] = [
  {
    id: 'MEM-01',
    location: 'Zone B — Downtown Subterranean Concourse',
    historicalIssue: 'During the 2024 Flash Inundation, subterranean concourse flooded within 12 minutes; Central Shelter S2 reached maximum capacity in under 45 minutes.',
    relevanceToCurrent: 'Historical constraint detected: Evacuation routes must bypass underground passageways; early diversion to secondary shelter required.',
    timestamp: 'October 14, 2024',
  },
  {
    id: 'MEM-02',
    location: 'Zone A — North Chemical Storage Facility',
    historicalIssue: 'Previous industrial fire in 2023 required an 800m exclusion perimeter due to chlorine gas heavier-than-air drift characteristics.',
    relevanceToCurrent: 'Ensure chemical plume drift vector is monitored continuously; advise upwind evacuation toward Sector 1.',
    timestamp: 'May 22, 2023',
  },
];

export const INITIAL_CAUSE_CHAIN: CauseChainNode[] = [
  {
    step: 1,
    title: 'Seismic Tremor (M 5.8)',
    description: 'Epicenter 12 km southwest at depth 8 km; triggers structural shockwaves.',
    severity: 'CRITICAL',
    active: true,
  },
  {
    step: 2,
    title: 'Storage Tank Flange Rupture & Building Collapse',
    description: 'Zone A hazardous tank valve failure + Zone B downtown facade shear.',
    severity: 'CRITICAL',
    active: true,
  },
  {
    step: 3,
    title: 'Road Alpha Obstruction & Bridge Vibration Alarms',
    description: 'Debris field and electrical hazard restrict primary transit artery.',
    severity: 'DANGER',
    active: true,
  },
  {
    step: 4,
    title: 'Multi-Agent Asset Contention (AMB-02)',
    description: 'Medical and Logistics agents simultaneously demand single ALS ambulance.',
    severity: 'DANGER',
    active: true,
  },
  {
    step: 5,
    title: 'Coordinator Compromise & Human-Supervised Dispatch',
    description: 'Algorithmic arbitration prioritizes severe crush trauma in Zone B while routing RV-01 to Zone A.',
    severity: 'MEDIUM',
    active: true,
  },
];

export const INITIAL_AUDIT_TRAIL: AuditTrailEntry[] = [
  {
    id: 'AUD-01',
    timestamp: '14:00:12',
    source: 'Seismic Telemetry Sensor',
    action: 'Regional seismic event detected and registered by Disaster Simulator',
    status: 'COMPLETED',
    details: 'Magnitude 5.8 registered across 4 monitoring stations.',
  },
  {
    id: 'AUD-02',
    timestamp: '14:01:05',
    source: 'Data Health Engine',
    action: 'Ground-truth telemetry validated; 2 conflicting reports flagged for officer verification',
    status: 'ALERT',
    details: 'Zone B casualty range (45-120) and Zone A road status flagged.',
  },
  {
    id: 'AUD-03',
    timestamp: '14:02:18',
    source: 'Medical Agent',
    action: 'Casualty triage matrix compiled; requested AMB-02 and MED-T1 for Zone B',
    status: 'COMPLETED',
    details: '18 casualties identified; 6 in hypovolemic shock.',
  },
  {
    id: 'AUD-04',
    timestamp: '14:02:45',
    source: 'Logistics Agent',
    action: 'Transit corridor analysis complete; requested AMB-02 and RV-01 for Zone A',
    status: 'COMPLETED',
    details: 'Evacuation corridor bottleneck flagged at Road Alpha.',
  },
  {
    id: 'AUD-05',
    timestamp: '14:03:10',
    source: 'Communication Agent',
    action: 'Public safety broadcast and evacuation advisories drafted for broadcast',
    status: 'COMPLETED',
    details: 'Tri-lingual advisories ready for EAS dispatch.',
  },
  {
    id: 'AUD-06',
    timestamp: '14:04:02',
    source: 'Conflict Engine',
    action: 'Deterministic contention identified on ALS Ambulance AMB-02',
    status: 'RESOLVED',
    details: 'Competing requests from Medical Agent (Zone B) and Logistics Agent (Zone A).',
  },
  {
    id: 'AUD-07',
    timestamp: '14:05:30',
    source: 'Coordinator Agent',
    action: 'Synthesized Proposed Response Plan and generated Primary & Backup alternatives',
    status: 'COMPLETED',
    details: 'Prioritized Zone B for AMB-02 based on medical mortality risk; assigned RV-01 to Zone A.',
  },
  {
    id: 'AUD-08',
    timestamp: '14:06:15',
    source: 'Human Approval System',
    action: 'Plan submitted to Authorized Emergency Response Officer for approval',
    status: 'PENDING',
    details: 'Waiting for officer review and signature before resource dispatch.',
  },
];

export const INITIAL_DEFAULT_STATE: SystemExecutionState = {
  scenarioTitle: 'Scenario Alpha: Regional Seismic Hazard & Hazardous Leak',
  activeEmergencyId: 'INITIAL_HAZARD',
  executionMode: 'SIMULATION_FALLBACK',
  stepIndex: 0,
  isRunning: false,
  zones: INITIAL_ZONES,
  resources: INITIAL_RESOURCES,
  agentStatuses: {
    'Medical Agent': {
      status: 'IDLE',
      currentTask: 'Standby for triage feed',
      latestRecommendation: 'Awaiting deployment assessment',
      lastMessage: 'Ready on bus channel MED-01',
      updatedAt: new Date().toISOString(),
      confidence: 0.94,
      overallSeverity: 'CRITICAL',
      zonesAnalyzedCount: 4,
    },
    'Logistics Agent': {
      status: 'IDLE',
      currentTask: 'Standby for transit route analysis',
      latestRecommendation: 'Awaiting evacuation orders',
      lastMessage: 'Ready on bus channel LOG-01',
      updatedAt: new Date().toISOString(),
      confidence: 0.91,
      overallSeverity: 'DANGER',
      zonesAnalyzedCount: 4,
    },
    'Communication Agent': {
      status: 'IDLE',
      currentTask: 'Monitoring public safety frequencies',
      latestRecommendation: 'Standby for broadcast directives',
      lastMessage: 'Ready on bus channel COM-01',
      updatedAt: new Date().toISOString(),
      confidence: 0.95,
      overallSeverity: 'DANGER',
      zonesAnalyzedCount: 4,
    },
    'Coordinator Agent': {
      status: 'IDLE',
      currentTask: 'Standby for cross-agent synthesis',
      latestRecommendation: 'Awaiting multi-agent submissions',
      lastMessage: 'Central bus broker initialized',
      updatedAt: new Date().toISOString(),
      confidence: 0.96,
    },
  },
  messages: [
    {
      message_id: 'MSG-INIT-001',
      from_agent: 'System Bus',
      to_agent: 'All Agents',
      message_type: 'UPDATE',
      timestamp: new Date().toISOString(),
      payload: {
        summary: 'RESQ-MIND Message Bus online. 4 independent agents connected to broker.',
      },
    },
  ],
  medicalOutput: null,
  logisticsOutput: null,
  communicationOutput: null,
  conflicts: [],
  constraintResult: null,
  coordinatorOutput: null,
  history: [],
  logs: [
    {
      id: 'LOG-001',
      timestamp: new Date().toISOString(),
      level: 'INFO',
      service: 'MessageBus',
      message: 'RESQ-MIND Orchestration Bus initialized.',
    },
  ],

  // NEW ADVANCED FEATURES STATE
  approvalState: INITIAL_APPROVAL_STATE,
  rescuePassports: INITIAL_PASS_PORTS,
  primaryBackupPlans: INITIAL_PRIMARY_BACKUP_PLANS,
  whatIfScenarios: INITIAL_WHAT_IF_SCENARIOS,
  activeWhatIfScenarioId: null,
  simulatedWhatIfPlan: null,
  dataHealthFields: INITIAL_DATA_HEALTH,
  conflictingReports: INITIAL_CONFLICTING_REPORTS,
  incidentMemory: INITIAL_INCIDENT_MEMORY,
  causeChain: INITIAL_CAUSE_CHAIN,
  auditTrail: INITIAL_AUDIT_TRAIL,
};
